language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - git submodule update --init --recursive
  - pip install setuptools six
# command to run tests
env:
  - PYTHONPATH=.
script:
  - python waferslim/tests/tests.py
  - python waferslim/tests/smoke.py
  - python setup.py build
  - python setup.py install
